---
- name: Prep environment for st2 install
  hosts: all
  environment: "{{ st2_proxy_env | default({}) }}"
  #become: true

  tasks:    
    - name: apt - Install python3-passlib
      apt: 
        pkg: python3-passlib 
        state: present
      ignore_errors: yes

    - name: apt - Install python-passlib
      apt: 
        pkg: python-passlib 
        state: present
      ignore_errors: yes

    - name: pip - Install latest passlib with pip
      pip: name=passlib
      ignore_errors: yes
    
    - name: yum - Install latest passlib with pip
      ansible.builtin.yum:
        name: python-passlib
        state: latest
      ignore_errors: yes