name: Deploy Testing for GHA Stackstorm

on:
  workflow_dispatch: {}
    
permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - id: deploy
      uses: bitovi/github-actions-deploy-stackstorm@main
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_DEVOPS_TRAINING }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEVOPS_TRAINING }}
        aws_default_region: ca-central-1
        dot_env: ${{ secrets.DOT_ENV }}
        domain_name: gha-stackstorm-testing1.com
        create_domain: true
        create_hosted_zone: true
