name: Deploy Testing for GHA Stackstorm

on:
  workflow_dispatch:
    inputs:
      domain_name:
        required: true
        default: gha-stackstorm-testing1.com
        type: string
      sub_domain:
        required: true
        default: gha-stackstorm-testing1.com
        type: string
      create_domain:
        required: true
        type: choice
        options:
          - false
          - true
      create_hosted_zone:
        required: true
        type: choice
        options:
          - false
          - true
      stack_destroy:
        required: true
        type: choice
        options:
          - false
          - true

      

    
permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - id: deploy
      uses: bitovi/github-actions-deploy-stackstorm@main
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_DEVOPS_TRAINING }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEVOPS_TRAINING }}
        aws_default_region: ca-central-1
        dot_env: ${{ secrets.DOT_ENV }}
        domain_name: ${{ github.event.inputs.domain_name }}
        sub_domain: ${{ github.event.inputs.sub_domain }}
        create_domain: ${{ github.event.inputs.create_domain }}
        create_hosted_zone: ${{ github.event.inputs.create_hosted_zone }}
        stack_destroy: ${{ github.event.inputs.stack_destroy }}

